[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "risingwave-pipeline-sdk"
version = "0.1.0"
description = "A Python SDK for building RisingWave data pipelines with multiple sources like PostgreSQL CDC and multiple sink destinations"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Ad Bean", email = "ad.bean@example.com" }]
keywords = [
    "risingwave",
    "cdc",
    "data-pipeline",
    "postgresql",
    "streaming",
    "iceberg",
    "s3",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["psycopg[binary]>=3.1", "pydantic>=2.7"]

[project.optional-dependencies]
dev = [
    "pytest>=8.2",
    "pytest-cov>=5.0",
    "ruff>=0.5",
    "build>=1.0.0",
    "twine>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/Ad-Bean/risingwave-pipeline-sdk"
Repository = "https://github.com/Ad-Bean/risingwave-pipeline-sdk"
Documentation = "https://github.com/Ad-Bean/risingwave-pipeline-sdk#readme"
Issues = "https://github.com/Ad-Bean/risingwave-pipeline-sdk/issues"

[tool.uv]
package = true

[tool.ruff]
line-length = 100
target-version = "py310"

[dependency-groups]
dev = ["build>=1.3.0", "twine>=6.1.0"]
